version: 0.2

env:
  git-credential-helper: yes

proxy:
    upload-artifacts: yes
    logs: yes
            
phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - npm install && npm run build
      - cd cdk && npm install && npm run build && npm run cdk synth && npm run deploy
  post_build:
    commands:
      - aws cloudformation --region eu-west-2 describe-stacks --stack-name CdkStack --query "Stacks[0].Outputs[?OutputKey=='quotesApiUrl']" --output text
