version: 0.2

env:
  git-credential-helper: yes

proxy:
    upload-artifacts: yes
    logs: yes
            
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install @types/node --save-dev
  build:
    commands:
      - npm install && npm run build
      - cd cdk && npm install && npm run build && npm run cdk synth && npm run deploy
